//HintName: EntityDto.g.cs
// <auto-generated/>
#nullable enable

namespace Application.Dtos
{
	public sealed partial class EntityDto
	{
		public int Id {get; set;}
		public string? Title {get; set;}
		public int[]? ArrayOfInts {get; set;}
	}
}
