//HintName: EntityDto.g.cs
// <auto-generated/>
#nullable enable

namespace Application.Dtos
{
	public sealed partial class EntityDto
	{
		public System.Guid Id {get; set;}
		public string? Description {get; set;}
	}
}
