//HintName: EntityDto.g.cs
// <auto-generated/>
#nullable enable

namespace Application.Dtos
{
	public sealed partial class EntityDto
	{
		public int Id {get; set;}
		public System.Collections.Generic.ICollection<string>? Items {get; set;}
	}
}
