//HintName: EntityDto.g.cs
// <auto-generated/>
#nullable enable

namespace Application.Dtos
{
	public sealed partial record EntityDto(
		int Id,
		string? Title,
		string? Description,
		System.Collections.Generic.ICollection<string>? Items
	);
}
