using SimpleDto.Generator.Common;
using SimpleDto.Generator.Extensions;
using SimpleDto.Generator.Templates.Abstractions;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SimpleDto.Generator.Templates.Attributes;

internal sealed class DtoMemberIgnoreAttributeTemplate : BaseAttributeTemplate
{
    public override string Namespace { get; } = Constants.AttributesNamespace;
    public override string AttributeFullName => $"{Namespace}.{AttributeName}";
    public override string AttributeName { get; } = "DtoMemberIgnoreAttribute";
    public override AttributeTargets AttributeTarget { get; } = AttributeTargets.Class;
    public override bool AllowMultiple { get; } = true;

    public override string Render()
    {
        return $$"""
            // <auto-generated/>
            #nullable enable
            {{Usings.Select(x => $"using {x};{"\n"}").Join()}}
            namespace {{Namespace}}
            {
            {{Constants.Tabulator}}[AttributeUsage(AttributeTargets.{{AttributeTarget}}, AllowMultiple = {{AllowMultiple.ToString().ToLower()}})]
            {{Constants.Tabulator}}internal sealed class DtoMemberIgnoreAttribute : Attribute
            {{Constants.Tabulator}}{
            {{Constants.Tabulator}}{{Constants.Tabulator}}public DtoMemberIgnoreAttribute(string propertyName)
            {{Constants.Tabulator}}{{Constants.Tabulator}}{
            {{Constants.Tabulator}}{{Constants.Tabulator}}{{Constants.Tabulator}}PropertyName = propertyName;
            {{Constants.Tabulator}}{{Constants.Tabulator}}}

            {{Constants.Tabulator}}{{Constants.Tabulator}}public DtoMemberIgnoreAttribute(Type propertyType)
            {{Constants.Tabulator}}{{Constants.Tabulator}}{
            {{Constants.Tabulator}}{{Constants.Tabulator}}{{Constants.Tabulator}}PropertyType = propertyType;
            {{Constants.Tabulator}}{{Constants.Tabulator}}}

            {{Constants.Tabulator}}{{Constants.Tabulator}}public string? PropertyName { get; }
            {{Constants.Tabulator}}{{Constants.Tabulator}}public Type? PropertyType { get; }
            {{Constants.Tabulator}}}
            }

            """;
    }
}