//HintName: DtoMemberIgnoreAttribute.g.cs
// <auto-generated/>
#nullable enable

using System;

namespace SimpleDto.Generator.Attributes
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]
    internal sealed class DtoMemberIgnoreAttribute : Attribute
    {
        public DtoMemberIgnoreAttribute(string propertyName)
        {
            PropertyName = propertyName;
        }

        public DtoMemberIgnoreAttribute(Type propertyType)
        {
            PropertyType = propertyType;
        }

        public string? PropertyName { get; }
        public Type? PropertyType { get; }
    }
}
